# fly.toml app configuration file generated for cameramenu-api-service on 2025-07-12T13:46:34+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'cameramenu-api-service'
primary_region = 'sin'

[build]

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
